# A simple function to create audit files.
# We want to have a file that can be produced within the pipeline that
# saves the changes happening to the data, like:
# data A has 80 lines, after filtering 1 it has 70 etc.
# This is not a log, but a reader friendly way to monitor the content of the
# data and the results.

#' audit_start
#' @name audit_start
#' @description Started of the audit file
#' @param dir_output Character where to save the file
#' @param file_name With default null, the output file name witll be the same
#' of the file in which function is invoked.
#' @param deap_name Character, name of the DEAP analysis
#' @param delete_old Boolean, delete_old if file exist
#' @param format Default txt
#' @return NULL
#' @export
audit_start <- function(
    dir_output = "data/audits",
    file_name = NULL,
    deap_name = NULL,
    delete_old = TRUE,
    format = ".txt") {
  if (is.null(file_name)) {
    file_name <- scriptName::current_filename()
    file_name <- basename(tools::file_path_sans_ext(file_name))
  }

  file_name_sens <- file_name
  file_name <- paste0(
    base::format(base::Sys.time(), "%Y-%m-%d_%H:%M_"), file_name
  )

  if (tools::file_ext(file_name) == "") {
    file_name <- paste0(file_name, format)
  }

  dir_output <- fs::path_norm(dir_output)
  if (!base::dir.exists(dir_output)) {
    base::dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
    logger::log_info(base::paste("Created directory:", dir_output))
  }

  audit_file <- list.files(
    dir_output,
    pattern = file_name_sens, full.names = TRUE
  )
  # create or clear file if delete_old = TRUE
  if (all(base::file.exists(audit_file)) && delete_old) {
    # remove old files with same name sens
    base::file.remove(audit_file)
    # create new file
    audit_file <- file.path(dir_output, file_name)
    base::file.create(audit_file)
    logger::log_info(base::paste("Created audit file:", audit_file))
  }

  start_time <- base::Sys.time()
  if (!is.null(deap_name)) {
    header <- paste0(
      "=== Audit for ", file_name_sens, " (", deap_name, ")", " ===\n",
      sep = " "
    )
  } else {
    header <- paste0("=== Audit for ", file_name_sens, " ===\n")
  }
  base::cat(
    header,
    file = audit_file,
    append = TRUE,
    sep = ""
  )
  base::cat(
    "Started at: ", base::format(start_time, "%Y-%m-%d %H:%M:%S"), "\n\n",
    file = audit_file,
    append = TRUE,
    sep = ""
  )

  # store path in an option so audit_add() can find it
  base::options(.current_audit_file = audit_file)
  base::options(.current_start_time = start_time)

  base::invisible(NULL)
  file_name
}


#' audit_add
#' @name audit_add
#' @description Add as a new lien and string whatever input
#' @param ... Objects to be pasted together into a single log line.
#' @return NULL
#' @export
audit_add <- function(...) {
  audit_file <- base::getOption(".current_audit_file")
  if (base::is.null(audit_file)) {
    stop(
      "audit_add() called before audit_start()",
      call. = FALSE
    )
  }

  args <- list(...)
  if (length(args) == 1 && data.table::is.data.table(args[[1]])) {
    utils::write.table(
      args[[1]], audit_file, append = FALSE,
      sep = " ", dec = ".",
      row.names = FALSE, col.names = TRUE
    )
  } else {
    msg <- base::paste0(...)

    base::cat(
      msg, "\n",
      file = audit_file,
      append = TRUE,
      sep = ""
    )

    base::invisible(NULL)
  }
}


#' Get release version
#' @return Character string with version info
#' @keywords internal
.get_release_version <- function() {
  # get the git tag if possible otherwise unknown
  tryCatch(
    {
      latest_tag <- base::system(
        "git describe --tags $(git rev-list --tags --max-count=1)",
        intern = TRUE
      )
    },
    error = function(e) {
      "unknown"
    }
  )
  tag_time <- base::system(
    base::sprintf(
      "git show -s --format=%%ai %s",
      base::shQuote(latest_tag)
    ),
    intern = TRUE
  )
  paste0(latest_tag, " (", tag_time, ")")
}

#' audit_end
#' @name audit_end
#' @description Close the audit file with summary and version stamp
#' @return NULL
#' @export
audit_end <- function() {
  audit_file <- base::getOption(".current_audit_file")
  start_time <- base::getOption(".current_start_time")
  if (base::is.null(audit_file)) {
    stop("audit_end() called before audit_start()", call. = FALSE)
  }
  release <- .get_release_version()

  base::cat(
    "\n", "Audit completed: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n",
    "\n",
    "Generated by: ", format(release), "\n",
    file = audit_file,
    append = TRUE,
    sep = ""
  )

  end_time <- base::Sys.time()
  duration <- difftime(end_time, start_time)

  base::cat(
    "Finished at: ",
    base::format(end_time, "%Y-%m-%d %H:%M:%S"), " mins\n",
    " Duration: ", round(duration, 2),
    "\n\n",
    file = audit_file,
    append = TRUE,
    sep = ""
  )

  # Clear options
  base::options(
    .current_audit_file = NULL
  )
  base::options(
    .current_start_time = NULL
  )

  logger::log_info(paste("Audit file saved:", audit_file))
  base::invisible(NULL)
}
