#' T3Pipeline Class
#'
#' @description
#' This class is responsible for managing the T3 pipeline, including loading
#' configuration files, executing steps, and cleaning up files.
#'
#' @details
#' The T3Pipeline class is designed to handle the T3 pipeline for semantic
#' harmonization. It loads configuration files, executes the steps defined in
#' the configuration, and cleans up files as needed.
#'
#' @export
t3_pipeline <- R6::R6Class(
  "T3Pipeline",
  inherit = pipeline,
  public = list(
    #' @field T3 Configuration for the T3 pipeline
    T3 = NULL,

    #' @description Initialize the T3 pipeline with a YAML configuration file.
    #' @param config_t3 Path to the YAML configuration file for T3
    #' @return An instance of T3Pipeline
    initialize = function(
      config_t3 = base::file.path("configuration", "config_T3.yaml")
    ) {
      logger::log_info("Initializing T3 class")
      self$T3 <- super$load_yaml(config_t3)
      self$config <- self$T3
      logger::log_debug("T3 config loaded")
    },

    #' @description Clean up files related to the T3 pipeline.
    #' @param dry_run Logical. Preview deletions by default.
    #' @return NULL
    clean = function(dry_run = TRUE) {
      # Implement if you need to clear intermediates, etc.
      # Keep no-op to preserve current caller expectations.
      logger::log_info("Removing T3 intermediate files")
      if (self$T3$cleanup$intermediate_data_file) {
        super$clean(content_to_delete = fs::path(
          self$T3$T3$root,
          self$T3$T3$intermediate
        ), dry_run = dry_run)
      }
      base::invisible(NULL)
    },

    #' @description Run the T3 pipeline.
    #' @return NULL
    run = function() {
      logger::log_info("Running T3 substeps via Pipeline engine")
      super$run_substeps(self$T3, step_key = "T3")
      logger::log_success("Step T3 completed successfully")
      base::invisible(NULL)
    },

    #' @description Delete data generated by the T3 pipeline.
    #' @param files Dictionary containing file to be deleted.
    #' @return NULL
    delete_data = function(files = NULL) {
      spec <- if (is.null(files)) self$T3$parquet_files else files
      logger::log_info("Deleting files.")
      super$delete_data(spec = spec)
      base::invisible(NULL)
    }
  )
)
